name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: Install packages
        run: yarn install

      - name: Test the app
        run: yarn test

      - name: Build the app
        run: yarn run build

      - name: Install Surge
        run: npm i surge -g

      - name: Deploy to surge
        run: surge ./dist ${{secrets.SURGE_DOMAIN}} --token ${{secrets.SURGE_TOKEN}}
