name: Deploy

on:
  push:
    branches: [main, ci-setup]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: Download production artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Install Surge
      - uses: actions/setup-node@v3
        with:
          node-version: 14
        run: npm i surge -g

      - name: Deploy to surge
        run: surge ./dist ${{secrets.SURGE_DOMAIN}} --token ${{secrets.SURGE_TOKEN}}
